# cnn_model_training-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cnn_model_training_deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cnn_model_training
  template:
    metadata:
      labels:
        app: cnn_model_training
    spec:
      containers:
      - name: cnn_model_training
        image: varoo0n/cnn_model_training:latest
        ports:
        - containerPort: 8080
