apiVersion: apps/v1
kind: Deployment
metadata:
  name: cnn-model-training-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cnn-model-training
  template:
    metadata:
      labels:
        app: cnn-model-training
    spec:
      containers:
      - name: cnn-model-training
        image: aloysias/cnn_model_training:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/app/models"
          name: models-storage
      volumes:
      - name: models-storage
        persistentVolumeClaim:
          claimName: models
