apiVersion: apps/v1
kind: Deployment
metadata:
  name: comparison-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comparison
  template:
    metadata:
      labels:
        app: comparison
    spec:
      containers:
      - name: comparison
        image: your-registry/comparison:latest
        ports:
        - containerPort: 80
