apiVersion: apps/v1
kind: Deployment
metadata:
  name: comparison-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comparison
  template:
    metadata:
      labels:
        app: comparison
    spec:
      containers:
      - name: comparison
        image: aloysias/comparison.py:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /data/saved_models
          name: models-storage
      volumes:
      - name: models-storage
        persistentVolumeClaim:
          claimName: models
