apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-augmentation-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-augmentation
  template:
    metadata:
      labels:
        app: data-augmentation
    spec:
      containers:
      - name: data-augmentation
        image: your-registry/data-augmentation:latest
        ports:
        - containerPort: 80

