apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-augmentation-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-augmentation
  template:
    metadata:
      labels:
        app: data-augmentation
    spec:
      containers:
      - name: data-augmentation
        image: edricneo/data_augmentation:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/app/models"
          name: models-storage
      volumes:
      - name: models-storage
        persistentVolumeClaim:
          claimName: models
