apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-training-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-training
  template:
    metadata:
      labels:
        app: model-training
    spec:
      containers:
      - name: model-training
        image: your-registry/model-training:latest
        ports:
        - containerPort: 80
