apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-inference-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-inference
  template:
    metadata:
      labels:
        app: model-inference
    spec:
      containers:
      - name: model-inference
        image: your-registry/model-inference:latest
        ports:
        - containerPort: 80
