apiVersion: apps/v1
kind: Deployment
metadata:
  name: transfer-learning-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transfer-learning
  template:
    metadata:
      labels:
        app: transfer-learning
    spec:
      containers:
      - name: transfer-learning
        image: amynyp/transfer_learning:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/app/models"
          name: models-storage
      volumes:
      - name: models-storage
        persistentVolumeClaim:
          claimName: models
